import type { FullProfileData } from '../../types';

export const SAMPLE_PROFILES: Record<string, { name: string; data: FullProfileData }> = {
  'jane-developer': {
    name: 'Jane Doe - Software Engineer',
    data: {
      profile: {
        id: 'sample-1',
        full_name: 'Jane Doe',
        email: 'jane.doe@example.com',
        phone: '+1 234 567 8900',
        location: 'San Francisco, CA',
        website: 'www.janedoe.com',
        linkedin: 'linkedin.com/in/janedoe',
        github: 'github.com/janedoe',
        headline: 'Senior Software Engineer',
        role: 'Full Stack Developer',
        summary: 'Experienced software engineer with 8+ years of expertise in building scalable web applications. Passionate about clean code, user experience, and mentoring junior developers.',
        photo_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        avatar_url: '',
        template: 'classic',
        slug: 'jane-doe',
        is_public: true,
      } as any,
      experiences: [
        {
          id: '1',
          position: 'Senior Software Engineer',
          company_name: 'Tech Corp',
          start_date: '2020-01',
          end_date: '2024-12',
          is_current: false,
          description: 'Led development of microservices architecture serving 1M+ users. Mentored team of 5 junior developers.',
        },
        {
          id: '2',
          position: 'Software Engineer',
          company_name: 'StartupXYZ',
          start_date: '2017-06',
          end_date: '2020-01',
          is_current: false,
          description: 'Built responsive web applications using React and Node.js. Implemented CI/CD pipelines.',
        },
      ],
      education: [
        {
          id: '1',
          institution_name: 'University of Technology',
          degree: 'Bachelor of Science',
          field_of_study: 'Computer Science',
          start_date: '2013-09',
          end_date: '2017-05',
          is_current: false,
          description: 'Graduated with honors. Focus on software engineering and algorithms.',
        },
      ],
      skills: [
        { id: '1', name: 'JavaScript', level: 'expert', category: 'technical' },
        { id: '2', name: 'React', level: 'expert', category: 'technical' },
        { id: '3', name: 'Node.js', level: 'advanced', category: 'technical' },
        { id: '4', name: 'TypeScript', level: 'advanced', category: 'technical' },
        { id: '5', name: 'Python', level: 'intermediate', category: 'technical' },
        { id: '6', name: 'Leadership', level: 'advanced', category: 'soft' },
      ],
      portfolioItems: [
        {
          id: '1',
          title: 'E-commerce Platform',
          description: 'Full-stack e-commerce solution with payment integration',
          url: 'https://example.com',
          image_url: '',
          tags: ['React', 'Node.js', 'MongoDB'],
        },
        {
          id: '2',
          title: 'Analytics Dashboard',
          description: 'Real-time analytics dashboard for business metrics',
          url: 'https://example.com',
          image_url: '',
          tags: ['React', 'D3.js', 'PostgreSQL'],
        },
      ],
      certifications: [],
      languages: [
        { id: 'l1', profile_id: 'sample-1', name: 'English', level: 'NATIVE' as const, is_native: true },
        { id: 'l2', profile_id: 'sample-1', name: 'Spanish', level: 'B1' as const, is_native: false },
      ],
      services: [],
      stats: [],
      stamps: [],
    } as unknown as FullProfileData,
  },
  'john-designer': {
    name: 'John Smith - UX Designer',
    data: {
      profile: {
        id: 'sample-2',
        full_name: 'John Smith',
        email: 'john.smith@example.com',
        phone: '+44 20 1234 5678',
        location: 'London, UK',
        website: 'johnsmith.design',
        linkedin: 'linkedin.com/in/johnsmith',
        github: '',
        headline: 'Senior UX/UI Designer',
        role: 'Product Designer',
        summary: 'Award-winning designer with 10+ years creating delightful user experiences. Specialized in mobile-first design and design systems. Led design teams at Fortune 500 companies.',
        photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        avatar_url: '',
        template: 'creative-bold',
        slug: 'john-smith',
        is_public: true,
      } as any,
      experiences: [
        {
          id: '1',
          position: 'Lead Product Designer',
          company_name: 'Design Studio Inc',
          start_date: '2019-03',
          end_date: '2024-12',
          is_current: false,
          description: 'Led design vision for flagship mobile app with 5M+ downloads. Established design system used across 15+ products.',
        },
        {
          id: '2',
          position: 'UX Designer',
          company_name: 'Creative Agency',
          start_date: '2014-06',
          end_date: '2019-03',
          is_current: false,
          description: 'Designed user interfaces for Fortune 500 clients. Conducted user research and usability testing.',
        },
      ],
      education: [
        {
          id: '1',
          institution_name: 'School of Visual Arts',
          degree: 'Master of Fine Arts',
          field_of_study: 'Interaction Design',
          start_date: '2012-09',
          end_date: '2014-05',
          is_current: false,
          description: 'Specialized in human-computer interaction and design thinking.',
        },
      ],
      skills: [
        { id: '1', name: 'Figma', level: 'expert', category: 'technical' },
        { id: '2', name: 'Sketch', level: 'expert', category: 'technical' },
        { id: '3', name: 'Adobe XD', level: 'advanced', category: 'technical' },
        { id: '4', name: 'User Research', level: 'expert', category: 'technical' },
        { id: '5', name: 'Design Systems', level: 'expert', category: 'technical' },
        { id: '6', name: 'Prototyping', level: 'advanced', category: 'technical' },
      ],
      portfolioItems: [
        {
          id: '1',
          title: 'Mobile Banking App',
          description: 'Complete redesign of banking app, increased user satisfaction by 40%',
          url: 'https://example.com/banking',
          image_url: '',
          tags: ['Mobile', 'FinTech', 'UI/UX'],
        },
        {
          id: '2',
          title: 'E-learning Platform',
          description: 'Designed educational platform serving 100K+ students',
          url: 'https://example.com/elearning',
          image_url: '',
          tags: ['Web', 'EdTech', 'Accessibility'],
        },
      ],
      certifications: [],
      languages: [
        { id: 'l1', profile_id: 'sample-2', name: 'English', level: 'NATIVE' as const, is_native: true },
        { id: 'l2', profile_id: 'sample-2', name: 'French', level: 'B2' as const, is_native: false },
      ],
      services: [],
      stats: [],
      stamps: [],
    } as unknown as FullProfileData,
  },
  'maria-manager': {
    name: 'Maria Garcia - Project Manager',
    data: {
      profile: {
        id: 'sample-3',
        full_name: 'Maria Garcia',
        email: 'maria.garcia@example.com',
        phone: '+34 91 123 4567',
        location: 'Madrid, Spain',
        website: 'mariagarcia.com',
        linkedin: 'linkedin.com/in/mariagarcia',
        github: '',
        headline: 'Senior Project Manager | PMP Certified',
        role: 'Project Manager',
        summary: 'Results-driven project manager with 12+ years leading cross-functional teams. Expert in Agile methodologies and stakeholder management. Successfully delivered 50+ projects on time and within budget.',
        photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
        avatar_url: '',
        template: 'professional-classic',
        slug: 'maria-garcia',
        is_public: true,
      } as any,
      experiences: [
        {
          id: '1',
          position: 'Senior Project Manager',
          company_name: 'Global Tech Solutions',
          start_date: '2018-01',
          end_date: '2024-12',
          is_current: false,
          description: 'Managed portfolio of enterprise projects worth $10M+. Led teams of 20+ people across multiple time zones.',
        },
        {
          id: '2',
          position: 'Project Manager',
          company_name: 'Innovation Hub',
          start_date: '2012-06',
          end_date: '2018-01',
          is_current: false,
          description: 'Coordinated software development projects using Scrum and Kanban. Improved team velocity by 35%.',
        },
      ],
      education: [
        {
          id: '1',
          institution_name: 'Business School Madrid',
          degree: 'MBA',
          field_of_study: 'Business Administration',
          start_date: '2010-09',
          end_date: '2012-05',
          is_current: false,
          description: 'Specialized in project management and organizational leadership.',
        },
      ],
      skills: [
        { id: '1', name: 'Project Management', level: 'expert', category: 'technical' },
        { id: '2', name: 'Agile/Scrum', level: 'expert', category: 'technical' },
        { id: '3', name: 'Stakeholder Management', level: 'expert', category: 'soft' },
        { id: '4', name: 'Risk Management', level: 'advanced', category: 'technical' },
        { id: '5', name: 'JIRA', level: 'advanced', category: 'technical' },
        { id: '6', name: 'Leadership', level: 'expert', category: 'soft' },
      ],
      portfolioItems: [
        {
          id: '1',
          title: 'Cloud Migration Project',
          description: 'Led migration of legacy systems to AWS, completed 2 months ahead of schedule',
          url: '',
          image_url: '',
          tags: ['Cloud', 'Migration', 'AWS'],
        },
        {
          id: '2',
          title: 'Digital Transformation Initiative',
          description: 'Managed company-wide digital transformation affecting 500+ employees',
          url: '',
          image_url: '',
          tags: ['Digital', 'Change Management', 'Strategy'],
        },
      ],
      certifications: [],
      languages: [
        { id: 'l1', profile_id: 'sample-3', name: 'Spanish', level: 'NATIVE' as const, is_native: true },
        { id: 'l2', profile_id: 'sample-3', name: 'English', level: 'C1' as const, is_native: false },
        { id: 'l3', profile_id: 'sample-3', name: 'Portuguese', level: 'B1' as const, is_native: false },
      ],
      services: [],
      stats: [],
      stamps: [],
    } as unknown as FullProfileData,
  },
};
