-- Fix portfolio_items table structure
-- Add missing columns if they don't exist

-- Ensure the table exists
CREATE TABLE IF NOT EXISTS public.portfolio_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL,
  title text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT portfolio_items_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Add missing columns
DO $$
BEGIN
    -- Add category column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'category'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN category text;
    END IF;

    -- Add link column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'link'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN link text;
    END IF;

    -- Add description column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'description'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN description text;
    END IF;

    -- Add image_url column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'image_url'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN image_url text;
    END IF;

    -- Add file_url column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'file_url'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN file_url text;
    END IF;

    -- Add sort_order column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'sort_order'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN sort_order integer DEFAULT 0;
    END IF;

    -- Add updated_at column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'portfolio_items'
        AND column_name = 'updated_at'
    ) THEN
        ALTER TABLE public.portfolio_items ADD COLUMN updated_at timestamp with time zone DEFAULT now();
    END IF;
END $$;

-- Create index on profile_id if it doesn't exist
CREATE INDEX IF NOT EXISTS portfolio_items_profile_id_idx ON public.portfolio_items(profile_id);

-- Create index on sort_order if it doesn't exist
CREATE INDEX IF NOT EXISTS portfolio_items_sort_order_idx ON public.portfolio_items(sort_order);

-- Enable RLS
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own portfolio items" ON public.portfolio_items;
DROP POLICY IF EXISTS "Users can insert their own portfolio items" ON public.portfolio_items;
DROP POLICY IF EXISTS "Users can update their own portfolio items" ON public.portfolio_items;
DROP POLICY IF EXISTS "Users can delete their own portfolio items" ON public.portfolio_items;

-- Create RLS policies
CREATE POLICY "Users can view their own portfolio items"
ON public.portfolio_items FOR SELECT
USING (auth.uid() = profile_id);

CREATE POLICY "Users can insert their own portfolio items"
ON public.portfolio_items FOR INSERT
WITH CHECK (auth.uid() = profile_id);

CREATE POLICY "Users can update their own portfolio items"
ON public.portfolio_items FOR UPDATE
USING (auth.uid() = profile_id);

CREATE POLICY "Users can delete their own portfolio items"
ON public.portfolio_items FOR DELETE
USING (auth.uid() = profile_id);
